#define checkkey\
if(!strcmpi(scan2,sun.name))\
word=sun;\
\
if(!strcmpi(scan2,got.name))\
word=got;\
\
if(!strcmpi(scan2,like.name))\
word=like;\
\
if(!strcmpi(scan2,you.name))\
word=you;\
\
if(!strcmpi(scan2,is.name))\
word=is;\
\
if(!strcmpi(scan2,lon.name))\
word=lon;\
\
if(!strcmpi(scan2,more.name))\
word=more;\
\
if(!strcmpi(love.name,scan2))\
word=love;\
\
if(!strcmpi(scan2,freinds.name))\
word=freinds;\
\
if(!strcmpi(scan2,freind.name))\
word=freind;\
\
if(!strcmpi(scan2,cant.name))\
word=cant;\
\
if(!strcmpi(scan2,cannot.name))\
word=cannot;\
\
if(!strcmpi(scan2,can.name))\
word=can;\
\
if(!strcmpi(scan2,me.name)) \
word=me;\
\
if(!strcmpi(scan2,feel.name))\
word=feel;\
\
if(!strcmpi(scan2,stupid.name))\
word=stupid;\
\
if(!strcmpi(scan2,boring.name))  \
word=boring;\
\
if(!strcmpi(scan2,idiot.name))\
word=idiot;\
\
if(!strcmpi(scan2,girlfreind.name))\
word=girlfreind;\
\
if(!strcmpi(scan2,boyfriend.name))  \
word=boyfreind;\
\
if(!strcmpi(scan2,depresed.name))      \
word=depresed;\
\
if(!strcmpi(scan2,unhappy.name))         \
word=unhappy;\
\
if(!strcmpi(scan2,bad.name))           \
word=bad;\
\
if(!strcmpi(scan2,mom.name))                 \
word=mom;\
\
if(!strcmpi(scan2,mother.name))                \
word=mother;\














